//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Bc.Model
{
    ///<summary>
    ///发布编译的指令
    ///</summary>
    [SugarTable("PublicCmd")]
    public class PublicCmd
    {
        public PublicCmd()
        {
        }

        /// <summary>
        /// 描述 : 发布编译的指令 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "发布编译的指令")]
        [SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
        public int Id { get; set; }

        /// <summary>
        /// 描述 : 发布站点编号 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "发布站点编号")]
        public string PublicNo { get; set; }


        /// <summary>
        /// 描述 : 指令 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "指令")]
        [SugarColumn(ColumnDescription = "指令", ColumnDataType = "varchar", Length = 2048)]
        public string Cmd { get; set; }


        [Display(Name = "分组")]
        public string GroupName { get; set; }

        [Display(Name = "排序")]
        [SugarColumn(ColumnDescription = "排序",ColumnDataType ="int",IsNullable =true,DefaultValue = "9999")]
        public int Sorter { get; set; }


    }
}