//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Bc.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("PublicToSite")]
    public class PublicToSite
    {
          public PublicToSite()
          {
          }

           /// <summary>
           /// 描述 : 发布站点对服务站点 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "发布站点对服务站点")]           
           [SugarColumn(IsPrimaryKey=true,IsIdentity=true)]
           public int Id {get;set;}

           /// <summary>
           /// 描述 : 发布站点编号 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "发布站点编号")]           
           public string PublicNo {get;set;}

           /// <summary>
           /// 描述 : 发布站点名称 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "发布站点名称")]           
           public string PublicSiteName {get;set;}

           /// <summary>
           /// 描述 : 服务站点编号 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "服务站点编号")]           
           public string ServerNo {get;set;}

           /// <summary>
           /// 描述 : 服务端站点名称 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "服务端站点名称")]           
           public string ServerSiteName {get;set;}

    }
}