//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Bc.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("Salary")]
    public class Salary
    {
          public Salary()
          {
          }

           /// <summary>
           /// 描述 : 薪资 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "薪资")]           
           [SugarColumn(IsPrimaryKey=true,IsIdentity=true)]
           public int Id {get;set;}

           /// <summary>
           /// 描述 : 员工姓名 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "员工姓名")]           
           public string UserName {get;set;}

           /// <summary>
           /// 描述 : 手机号 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "手机号")]           
           public string Mobile {get;set;}

           /// <summary>
           /// 描述 : 编号 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "编号")]           
           public string UserNo {get;set;}

           /// <summary>
           /// 描述 : 访问地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "访问地址")]           
           public string BroswerUrl {get;set;}

           /// <summary>
           /// 描述 : 月份 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "月份")]           
           public string Month {get;set;}

           /// <summary>
           /// 描述 : 授权码 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "授权码")]           
           public string Code {get;set;}

           /// <summary>
           /// 描述 : 部门 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门")]           
           public string Dept {get;set;}

           /// <summary>
           /// 描述 : 岗位 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "岗位")]           
           public string Post {get;set;}

           /// <summary>
           /// 描述 : 出勤天数 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "出勤天数")]           
           public string DutyDays {get;set;}

           /// <summary>
           /// 描述 : 基本工资 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "基本工资")]           
           public string BasicMoney {get;set;}

           /// <summary>
           /// 描述 : 岗位工资 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "岗位工资")]           
           public string DutyMoney {get;set;}

           /// <summary>
           /// 描述 : 绩效工资 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "绩效工资")]           
           public string MeritMoney {get;set;}

           /// <summary>
           /// 描述 : 住房补贴 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "住房补贴")]           
           public string HouseMoney {get;set;}

           /// <summary>
           /// 描述 : 保密费 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "保密费")]           
           public string SecretMoney {get;set;}

           /// <summary>
           /// 描述 : 周末加班费 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "周末加班费")]           
           public string WeekendOverTimeMoney {get;set;}

           /// <summary>
           /// 描述 : 工龄补贴 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "工龄补贴")]           
           public string WorkAgeMoney {get;set;}

           /// <summary>
           /// 描述 : 提成 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "提成")]           
           public string TiChengMoney {get;set;}

           /// <summary>
           /// 描述 : 奖金 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "奖金")]           
           public string PrizeMoney {get;set;}

           /// <summary>
           /// 描述 : 全勤奖 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "全勤奖")]           
           public string FullDutyMoney {get;set;}

           /// <summary>
           /// 描述 : 加班费 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "加班费")]           
           public string OverTimeMoney {get;set;}

           /// <summary>
           /// 描述 : 午餐补贴 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "午餐补贴")]           
           public string LunchMoney {get;set;}

           /// <summary>
           /// 描述 : 晚餐补贴 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "晚餐补贴")]           
           public string DinnerMoney {get;set;}

           /// <summary>
           /// 描述 : 通讯补贴 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "通讯补贴")]           
           public string CallMoney {get;set;}

           /// <summary>
           /// 描述 : 出车津贴 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "出车津贴")]           
           public string CarMoney {get;set;}

           /// <summary>
           /// 描述 : 其他津贴 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "其他津贴")]           
           public string OtherJtMoney {get;set;}

           /// <summary>
           /// 描述 : 应发薪资 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "应发薪资")]           
           public string ShouldMoney {get;set;}

           /// <summary>
           /// 描述 : 迟到次数 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "迟到次数")]           
           public string LaterDays {get;set;}

           /// <summary>
           /// 描述 : 事假 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "事假")]           
           public string EventHolidays {get;set;}

           /// <summary>
           /// 描述 : 未打卡 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "未打卡")]           
           public string NoCard {get;set;}

           /// <summary>
           /// 描述 : 病假 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "病假")]           
           public string Silk {get;set;}

           /// <summary>
           /// 描述 : 其他扣款 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "其他扣款")]           
           public string OtherDiscountMoney {get;set;}

           /// <summary>
           /// 描述 : 养老扣款 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "养老扣款")]           
           public string FeeOldMoney {get;set;}

           /// <summary>
           /// 描述 : 公积金扣款 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "公积金扣款")]           
           public string PublicJiMoney {get;set;}

           /// <summary>
           /// 描述 : 实际发款金额 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "实际发款金额")]           
           public string ActualMoney {get;set;}

           /// <summary>
           /// 描述 : 发送短信次数 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "发送短信次数")]           
           public int? SmsCc {get;set;}

           /// <summary>
           /// 描述 : 更新时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "更新时间")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 : 个税 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "个税")]           
           public string Tax {get;set;}

    }
}