//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Bc.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("ServerApp")]
    public class ServerApp
    {
          public ServerApp()
          {
          }

           /// <summary>
           /// 描述 : 服务端 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "服务端")]           
           [SugarColumn(IsPrimaryKey=true,IsIdentity=true)]
           public int Id {get;set;}

           /// <summary>
           /// 描述 : 站点编号 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "站点编号")]           
           public string No {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string ServerName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string IP {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string Port {get;set;}

           /// <summary>
           /// 描述 : 1生产端 2测试端 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "1生产端 2测试端")]           
           public int Env {get;set;}

           /// <summary>
           /// 描述 : 更新实际 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "更新实际")]           
           public DateTime UpdateTime {get;set;}

    }
}