//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Bc.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("UserInfo")]
    public class UserInfo
    {
          public UserInfo()
          {
          }

           /// <summary>
           /// 描述 : 员工Id 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "员工Id")]           
           [SugarColumn(IsPrimaryKey=true,IsIdentity=true)]
           public int Id {get;set;}

           /// <summary>
           /// 描述 : 员工编号 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "员工编号")]           
           public string UserNo {get;set;}

           /// <summary>
           /// 描述 : 创建时间 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "创建时间")]           
           public DateTime CreateTime {get;set;}

           /// <summary>
           /// 描述 : 更新时间 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "更新时间")]           
           public DateTime UpdateTime {get;set;}

           /// <summary>
           /// 描述 : 微信Id 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "微信Id")]           
           public string WxOpenId {get;set;}

           /// <summary>
           /// 描述 : 手机号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "手机号")]           
           public string Mobile {get;set;}

           /// <summary>
           /// 描述 : 性别 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "性别")]           
           public string Sex {get;set;}

           /// <summary>
           /// 描述 : 出生日期 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "出生日期")]           
           public string BirthDay {get;set;}

           /// <summary>
           /// 描述 : 部门 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门")]           
           public string DeptName {get;set;}

           /// <summary>
           /// 描述 : 岗位 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "岗位")]           
           public string Duty {get;set;}

           /// <summary>
           /// 描述 : 授权码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "授权码")]           
           public string AuthCode {get;set;}

           /// <summary>
           /// 描述 : 微信名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "微信名称")]           
           public string WxNickName {get;set;}

           /// <summary>
           /// 描述 : 审核通过：1审核通过  0待审核 2审核不通过 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "审核通过：1审核通过  0待审核 2审核不通过")]           
           public int Status {get;set;}

           /// <summary>
           /// 描述 : 是否超级管理员 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "是否超级管理员")]           
           public int IsSupper {get;set;}

           /// <summary>
           /// 描述 : 员工姓名 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "员工姓名")]           
           public string UserName {get;set;}

           /// <summary>
           /// 描述 : 岗位类型 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "岗位类型")]           
           public string DutyType {get;set;}

           /// <summary>
           /// 描述 : 名族 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "名族")]           
           public string MingZu {get;set;}

           /// <summary>
           /// 描述 : 结婚情况 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "结婚情况")]           
           public string Webbing {get;set;}

           /// <summary>
           /// 描述 : 身份证号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "身份证号")]           
           public string CodeID {get;set;}

           /// <summary>
           /// 描述 : 员工密码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "员工密码")]           
           public string Pwd {get;set;}

    }
}