//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Bc.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("WebSiteBinding")]
    public class WebSiteBinding
    {
          public WebSiteBinding()
          {
          }

           /// <summary>
           /// 描述 : 站点绑定 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "站点绑定")]           
           [SugarColumn(IsPrimaryKey=true,IsIdentity=true)]
           public int Id {get;set;}

           /// <summary>
           /// 描述 : 编号 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "编号")]           
           public string No {get;set;}

           /// <summary>
           /// 描述 : 端口 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "端口")]           
           public string Port {get;set;}

           /// <summary>
           /// 描述 : 服务器 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "服务器")]           
           public string ServerIP {get;set;}

           /// <summary>
           /// 描述 : 协议:http/https 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "协议:http/https")]           
           public string Protocol {get;set;}

           /// <summary>
           /// 描述 : 主机名 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "主机名")]           
           public string HostName {get;set;}

    }
}