//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Bc.Model;
using Bc.Common.Utilities;
using Bc.Model.Dto;
using System.Collections.Generic;
using Bc.Model.View;
using System.Data;

namespace Bc.Bussiness.IService
{
    public interface IDbConfigService : IBaseService<DbConfig>
    {

        #region CustomInterface 

        /// <summary>   
        /// 查询分页   
        /// </summary> 
        /// <returns></returns>  
        PagedInfo<DbConfig> QueryPages(DbConfigDto parm);

        /// <summary>
        /// 获取表字段
        /// </summary>
        /// <param name="config"></param>
        /// <param name="database"></param>
        /// <param name="table"></param>
        /// <returns></returns>
        List<TableInfo> GetTableColumn(string configno, string database, string table);
        /// <summary>
        /// 获取数据库
        /// </summary>
        /// <param name="configno"></param>
        /// <returns></returns>
        List<string> GetDatabaseList(string configno);

        /// <summary>
        /// 获取表行数
        /// </summary>
        /// <param name="configno"></param>
        /// <param name="database"></param>
        /// <param name="tablename"></param>
        /// <returns></returns>
          DataTable GetTableRows(string configno, string database = "", string tablename = "");
        #endregion

    }
}
