//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Bc.Model;
using Bc.Model.Dto;
using Bc.Model.View;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;
using System;

namespace Bc.Bussiness
{
    public interface ISys_LogsService : IBaseService<Sys_Logs>
    {
        int AddInfo(Sys_Logs info);
        /// <summary>
        /// 查询vin信息（分页）
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
         PagedInfo<Sys_Logs> QueryPages(Sys_LogsDto parm);
    }
}
