//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Bc.Model;
using Bc.Model.Dto;
using Bc.Model.View;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;
using System;

namespace Bc.Bussiness
{
    public interface IUserInfoService : IBaseService<UserInfo>
    {

        #region CustomInterface 

        /// <summary>
        /// 上传工资条
        /// </summary>
        /// <param name="lst"></param>
        /// <param name="msg"></param>
        /// <returns></returns>
        int UploadUserInfo(List<string> lst, ref string msg);



        /// <summary>
        /// 登录
        /// </summary>
        /// <param name="lst"></param>
        /// <param name="msg"></param>
        /// <returns></returns>
        int Login(string username, string pwd, string scode, ref string msg, ref string code, ref JwtUserInfo jwtInfo);

        #endregion

    }
}
